version: '1.1.3.{build}'

os: Visual Studio 2017

environment:
  matrix:
  - QT5: C:\Qt\5.9\msvc2017_64

matrix:
  fast_finish: false
  
before_build:
- '%QT5%\bin\qtenv2.bat'
- qmake -v

#- for /f %%i in ('git --git-dir=%APPVEYOR_BUILD_FOLDER%\.git describe') do set GLOGG_VERSION=%%i
#- for /f %%i in ('git --git-dir=%APPVEYOR_BUILD_FOLDER%\.git rev-parse --short HEAD') do set GLOGG_COMMIT=%%i

- set PATH=C:\Program Files (x86)\NSIS;%PATH%

# VS2017
- call "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\Common7\Tools\vsdevcmd" -arch=x64

build_script:
- cd %APPVEYOR_BUILD_FOLDER%
- qmake -r VERSION=%APPVEYOR_BUILD_VERSION%
- nmake.exe

after_build:
- xcopy %QT5%\bin\Qt5Core.dll %APPVEYOR_BUILD_FOLDER%\release\ /y
- xcopy %QT5%\bin\Qt5Gui.dll %APPVEYOR_BUILD_FOLDER%\release\ /y
- xcopy %QT5%\bin\Qt5Network.dll %APPVEYOR_BUILD_FOLDER%\release\ /y
- xcopy %QT5%\bin\Qt5Widgets.dll %APPVEYOR_BUILD_FOLDER%\release\ /y
- xcopy %QT5%\bin\Qt5Concurrent.dll %APPVEYOR_BUILD_FOLDER%\release\ /y
- md %APPVEYOR_BUILD_FOLDER%\release\platforms
- xcopy %QT5%\plugins\platforms\qminimal.dll %APPVEYOR_BUILD_FOLDER%\release\platforms\ /y
- xcopy %QT5%\plugins\platforms\qwindows.dll %APPVEYOR_BUILD_FOLDER%\release\platforms\ /y
- 7z a klogg-%APPVEYOR_BUILD_VERSION%.zip -r %APPVEYOR_BUILD_FOLDER%\release\*.exe %APPVEYOR_BUILD_FOLDER%\release\*.dll %APPVEYOR_BUILD_FOLDER%\README.md %APPVEYOR_BUILD_FOLDER%\COPYING
- makensis -DVERSION=%APPVEYOR_BUILD_VERSION% %APPVEYOR_BUILD_FOLDER%\klogg.nsi

artifacts:
  - path: klogg-%APPVEYOR_BUILD_VERSION%.zip
    name: klogg
  - path: klogg-%APPVEYOR_BUILD_VERSION%-setup.exe
    name: installer
